version: "3.9"
services:
  neo4j:
    image: neo4j:latest
    restart: always
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/your_password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data1:/data
volumes:
  neo4j_data1:
