version: "3.9"
services:
  neo4j:
    image: neo4j:5.21.0
    restart: always
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/your_password
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:
